<html>
<head>
	<title>Index</title>
</head>
<body>
	<h1>ENLASES</h1>
	<ul>
	<li> <a href="1.PHP">EJERCICIO 1</a></li>
	<li> <a href="2.PHP">EJERCICIO 2</a></li>
	<li> <a href="3.PHP">EJERCICIO 3</a></li>
	<li> <a href="4.PHP">EJERCICIO 4</a></li>
	<li> <a href="5.PHP">EJERCICIO 5</a></li>
	<li> <a href="6.PHP">EJERCICIO 6</a></li>
	<li> <a href="7.PHP">EJERCICIO 7</a></li>
	<li> <a href="7-1.PHP">EJERCICIO 7.1</a></li>
	<li> <a href="8.PHP">EJERCICIO 8</a></li>
	<li> <a href="9.PHP">EJERCICIO 9</a></li>
	<li> <a href="9-1.PHP">EJERCICIO 9.1</a></li>
	<li> <a href="10.PHP">EJERCICIO 10</a></li>
	<li> <a href="10-1.PHP">EJERCICIO 10.1</a></li>
	<li> <a href="10-2.PHP">EJERCICIO 10.2</a></li>
	<li> <a href="11.PHP">EJERCICIO 11</a></li>
	<li> <a href="11-1.PHP">EJERCICIO 11.1</a></li>
	<li> <a href="11-2.PHP">EJERCICIO 11.2</a></li>
	<li> <a href="12.PHP">EJERCICIO 12</a></li>
	<li> <a href="12-1.PHP">EJERCICIO 12.1</a></li>

</ul>
</body>
</html>